version: '2'
services:
  web:
    image: nginx:latest
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/site:cached"
      - "./site.conf:/etc/nginx/conf.d/default.conf"
  php:
    build: .
    volumes:
      - ".:/var/www/site:cached"
    links:
      - db:mysql
      - maildev
    environment:
      - DB_NAME=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - WP_ENV=development
      - WP_HOME=http://localhost:8080
      - WP_SITEURL=http://localhost:8080/wp
  db:
    image: mariadb:5.5.56
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
  maildev:
    image: djfarrelly/maildev
    ports:
      - 8282:80
