version: '2'
services:
  server:
    build: .
    volumes: 
      - /var/www/html/vendor
      - /var/www/html/web/wp
      - /var/www/html/web/app/mu-plugins
      - /var/www/html/web/app/plugins
      - .:/var/www/html
    links:
      - db:mysql
    ports:
      - "8080:80"
    environment:
      - DB_NAME=wordpress
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - WP_ENV=development
      - WP_HOME=http://localhost:8080
      - WP_SITEURL=http://localhost:8080/wp
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
